=== Fellfalla/Akomi.Tapako/04_Systemintegration/Javelin Demo/drivers/iodd/default/IODD-Primitives1.0.1.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.io-link.com/IODD/2009/11" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:iodd="http://www.io-link.com/IODD/2009/11" targetNamespace="http://www.io-link.com/IODD/2009/11" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0.1">
	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
	<xsd:simpleType name="IdT">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[A-Za-z][A-Za-z0-9 _-]*[A-Za-z0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="RefT">
		<xsd:restriction base="xsd:token">
			<xsd:pattern value="[A-Za-z][A-Za-z0-9 _-]*[A-Za-z0-9]"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="SubindexT">
		<xsd:restriction base="xsd:unsignedByte">
			<xsd:minInclusive value="1"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="CharacterEncodingT">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="UTF-8"/>
			<xsd:enumeration value="US-ASCII"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="VersionT">
		<xsd:restriction base="xsd:string">
			<xsd:pattern value="V\d+(\.\d+)+"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:simpleType name="AccessRightsT">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="ro"/>
			<xsd:enumeration value="rw"/>
			<xsd:enumeration value="wo"/>
		</xsd:restriction>
	</xsd:simpleType>
	<xsd:complexType name="TextDefinitionT">
		<xsd:attribute name="id" type="IdT" use="required"/>
		<xsd:attribute name="value" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="TextRefT">
		<xsd:attribute name="textId" type="RefT" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="CollectionT"/>
	<xsd:complexType name="StampT">
		<xsd:sequence>
			<xsd:element name="Checker">
				<xsd:complexType>
					<xsd:attribute name="name" type="xsd:token" use="required"/>
					<xsd:attribute name="version" type="VersionT" use="required"/>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
		<xsd:attribute name="crc" type="xsd:unsignedInt" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ConditionT">
		<xsd:attribute name="variableId" type="RefT" use="required"/>
		<xsd:attribute name="subindex" type="SubindexT" use="optional"/>
		<xsd:attribute name="value" type="xsd:unsignedByte" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ExternalTextCollectionT">
		<xsd:complexContent>
			<xsd:extension base="CollectionT">
				<xsd:sequence>
					<xsd:element name="PrimaryLanguage" type="PrimaryLanguageT"/>
					<xsd:element name="Language" type="LanguageT" minOccurs="0" maxOccurs="unbounded">
						<xsd:unique name="Language_id">
							<xsd:selector xpath="iodd:Text"/>
							<xsd:field xpath="@id"/>
						</xsd:unique>
					</xsd:element>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:complexType name="DocumentInfoT">
		<xsd:annotation>
			<xsd:documentation>This type defines document information.</xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="version" type="VersionT" use="required"/>
		<xsd:attribute name="releaseDate" type="xsd:date" use="required"/>
		<xsd:attribute name="copyright" type="xsd:string" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ObjectT">
		<xsd:attribute name="id" type="IdT" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="ExternalTextDocumentT">
		<xsd:annotation>
			<xsd:documentation>This type defines the structure of the file that contains external language dependent text definitions. One file can contain texts of only one language.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="DocumentInfo" type="DocumentInfoT" minOccurs="0"/>
			<xsd:element name="Language" type="LanguageT">
				<xsd:unique name="ExternalTextDocument_Language_id">
					<xsd:selector xpath="iodd:Text"/>
					<xsd:field xpath="@id"/>
				</xsd:unique>
			</xsd:element>
			<xsd:element name="Stamp" type="StampT">
				<xsd:annotation>
					<xsd:documentation>Filled out by the IODD Checker.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:element name="ExternalTextDocument" type="ExternalTextDocumentT">
		<xsd:annotation>
			<xsd:documentation>This defines the root element of the file that contains external text definitions.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="LanguageT">
		<xsd:sequence>
			<xsd:element name="Text" type="TextDefinitionT" maxOccurs="unbounded"/>
		</xsd:sequence>
		<xsd:attribute ref="xml:lang" use="required"/>
	</xsd:complexType>
	<xsd:complexType name="PrimaryLanguageT">
		<xsd:complexContent>
			<xsd:restriction base="LanguageT">
				<xsd:sequence>
					<xsd:element name="Text" type="TextDefinitionT" maxOccurs="unbounded"/>
				</xsd:sequence>
<!--				<xsd:attribute ref="xml:lang" use="required" fixed="en"/> -->
			</xsd:restriction>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="BitCountT">
		<xsd:restriction base="xsd:unsignedShort"/>
	</xsd:simpleType>
</xsd:schema>

=== Fellfalla/Akomi.Tapako/04_Systemintegration/2016-10-27 Tapako Build/DriverRepository/iodd/default/IODD-StandardDefinitions1.0.1-de.xml
<?xml version="1.0" encoding="UTF-8"?>
<ExternalTextDocument xmlns="http://www.io-link.com/IODD/2009/11" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.io-link.com/IODD/2009/11 IODD-Primitives1.0.1.xsd">
	<!-- 2010-09-17 correction: completed translation to german -->
	<DocumentInfo version="V1.0.1" releaseDate="2010-09-20" copyright="IO-Link Consortium"/>
	<Language xml:lang="de">
		<Text id="STD_TI_Reserved" value="Reserviert"/>
		<!-- Variables -->
		<Text id="STD_TI_DirectParameters1" value="Direkte Parameter 1"/>
		<Text id="STD_TI_MasterCycleTime" value="Master Zykluszeit"/>
		<Text id="STD_TI_MinCycleTime" value="Minimale Zykluszeit"/>
		<Text id="STD_TI_FrameCapability" value="Telegramm-Fähigkeit"/>
		<Text id="STD_TI_IOLinkRevisionID" value="IO-Link Versions-ID"/>
		<Text id="STD_TI_ProcessDataIn" value="Prozessdatenlänge Eingang"/>
		<Text id="STD_TI_ProcessDataOut" value="Prozessdatenlänge Ausgang"/>
		<Text id="STD_TI_VendorID1" value="Hersteller-ID 1"/>
		<Text id="STD_TI_VendorID2" value="Hersteller-ID 2"/>
		<Text id="STD_TI_DeviceID1" value="Geräte-ID 1"/>
		<Text id="STD_TI_DeviceID2" value="Geräte-ID 2"/>
		<Text id="STD_TI_DeviceID3" value="Geräte-ID 3"/>
		<Text id="STD_TI_DirectParameters2" value="Direkte Parameter 2"/>
		<Text id="STD_TI_DeviceSpecific_1" value="Gerätespezifischer Parameter 1"/>
		<Text id="STD_TI_DeviceSpecific_2" value="Gerätespezifischer Parameter 2"/>
		<Text id="STD_TI_DeviceSpecific_3" value="Gerätespezifischer Parameter 3"/>
		<Text id="STD_TI_DeviceSpecific_4" value="Gerätespezifischer Parameter 4"/>
		<Text id="STD_TI_DeviceSpecific_5" value="Gerätespezifischer Parameter 5"/>
		<Text id="STD_TI_DeviceSpecific_6" value="Gerätespezifischer Parameter 6"/>
		<Text id="STD_TI_DeviceSpecific_7" value="Gerätespezifischer Parameter 7"/>
		<Text id="STD_TI_DeviceSpecific_8" value="Gerätespezifischer Parameter 8"/>
		<Text id="STD_TI_DeviceSpecific_9" value="Gerätespezifischer Parameter 9"/>
		<Text id="STD_TI_DeviceSpecific_10" value="Gerätespezifischer Parameter 10"/>
		<Text id="STD_TI_DeviceSpecific_11" value="Gerätespezifischer Parameter 11"/>
		<Text id="STD_TI_DeviceSpecific_12" value="Gerätespezifischer Parameter 12"/>
		<Text id="STD_TI_OffsetTime" value="Offsetzeit"/>
		<Text id="STD_TI_SystemCommand" value="Systemkommando"/>
		<Text id="STD_TI_SystemCommand_DeviceReset" value="Gerät rücksetzen"/>
		<Text id="STD_TI_SystemCommand_ApplicationReset" value="Anwendung rücksetzen"/>
		<Text id="STD_TI_SystemCommand_RestoreFactorySetting" value="Auslieferungszustand wiederherstellen"/>
		<Text id="STD_TI_VendorName" value="Herstellername"/>
		<Text id="STD_TI_VendorText" value="Herstellertext"/>
		<Text id="STD_TI_ProductName" value="Produktname"/>
		<Text id="STD_TI_ProductID" value="Produkt-ID"/>
		<Text id="STD_TI_ProductText" value="Produkttext"/>
		<Text id="STD_TI_SerialNumber" value="Seriennummer"/>
		<Text id="STD_TI_HardwareRevision" value="Hardwareversion"/>
		<Text id="STD_TI_FirmwareRevision" value="Firmwareversion"/>
		<Text id="STD_TI_ApplicationSpecificName" value="Anwendungsspezifischer Name"/>
		<Text id="STD_TI_ErrorCount" value="Fehlerzähler"/>
		<Text id="STD_TI_LastEvent" value="Letztes Ereignis"/>
		<Text id="STD_TI_LastEvent_Qualifier" value="Ereigniskennzeichnung"/>
		<Text id="STD_TI_LastEvent_Code" value="Ereigniscode"/>
		<Text id="STD_TI_ProcessDataInput" value="Prozessdaten Eingang"/>
		<Text id="STD_TI_ProcessDataOutput" value="Prozessdaten Ausgang"/>
	</Language>
	<Stamp crc="601345229"><Checker name="IODD-Checker V1.0.4" version="V1.0.4.0"/></Stamp>
</ExternalTextDocument>
